/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE RESOURCE1

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "config.h"

#include "POUS.c"

BOOL GETTIMESYNC;
PLC_PRG RESOURCE1__PLC_TASK_INSTANCE;
#define PLC_TASK_INSTANCE RESOURCE1__PLC_TASK_INSTANCE

void RESOURCE1_init__(void) {
  BOOL retain;
  retain = 0;
  
  GETTIMESYNC = __BOOL_LITERAL(FALSE);
  PLC_PRG_init__(&PLC_TASK_INSTANCE,retain);
}

void RESOURCE1_run__(unsigned long tick) {
  GETTIMESYNC = !(tick % 1);
  if (GETTIMESYNC) {
    PLC_PRG_body__(&PLC_TASK_INSTANCE);
  }
}

